name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, ubuntu-20.04, windows-latest, macOS-latest, macos-11.0 ]

        steps:
        - uses: actions/checkout@v2
        - name: Test
          shell: pwsh
          run: ./tasks.ps1 -Task Test -Bootstrap
    testpowershell:
        runs-on: [ windows-latest ]
        
        steps:
        - uses: actions/checkout@v2
        - name: testpowershell
          shell: powershell
          run: ./tasks.ps1 -Task Test -Bootstrap
    analyze:
            runs-on: [ windows-latest ]

            steps:
            - uses: actions/checkout@v2
            - name: Analyze
              shell: pwsh
              run: ./tasks.ps1 -Task Analyze -Bootstrap