name: CI

on:
    push:
        branches: [ master ]
    pull_request:
        branches: [ master ]

jobs:
    test:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ ubuntu-latest, windows-latest, macOS-latest ]

        steps:
        - uses: actions/checkout@v2
        - name: Test
          shell: pwsh
          run: ./tasks.ps1 -Task Test -Bootstrap